version: 2
jobs:
  build:
    docker:
      - image: dockbuild/ubuntu1804-gcc7:latest

    steps:
      - checkout

      - run:
          name: Make build directory
          command: mkdir build

      - run:
          name: CMake
          command: 'cmake ..'
          working_directory: build

      - run:
          name: Make
          command: make VERBOSE=1
          working_directory: build

      - run:
          name: Quick test
          command: ctest -VV
          working_directory: build

      - run:
          name: Full tests
          command: 'time ./eevm_tests -ns -d'
          working_directory: build
          environment:
              TEST_DIR: '../3rdparty/test_cases/'
